---
# OS Details
os: linux
language: python
python: '3.8'

cache:
  pip: true

# Install ansible and ansible-lint
install:
  - pip install ansible
  - pip install ansible-lint

# more advanced testing is currently handled with
#  github actions. The gh-actions for our test are there:
#  https://github.com/roles-ansible and are tagged
#  with 'github-actions'  --> https://github.com/search?q=topic%3Agithub-actions+org%3Aroles-ansible&type=Repositories
script:
  - ansible-lint .
  - echo -e "\n\n\n\n\nWe use github actions for more detailed tests.\n\nMore details about that in our github repo at:\nhttps://github.com/roles-ansible/role-ranger/actions\n\n\n\n\n\n"

notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
