name: Ansible check alpine:latest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ansible check with alpine:latest
      uses: roles-ansible/check-ansible-alpine-latest-action@master
      with:
        targets: "./"
